sudo: false
language: go


go:
    - 1.x
    - 1.7
    - 1.5
    - 1.3
    - master


before_install:
    - openssl aes-256-cbc -K $encrypted_9ef8bed50dde_key -iv $encrypted_9ef8bed50dde_iv -in private.go.enc -out private.go -d

install:
    - go get golang.org/x/tools/cmd/cover


script:
    - go test -v -cover
